version: '3.9'
services:
  postgres: 
    image: postgres:14.3
    restart: always
    container_name: product-api-db
    ports:
    - "5432:5432"
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: product-api-db
    volumes:
        - ./postgres:/var/lib/postgresql/data